# Generated by Django 4.0.4 on 2022-05-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('line_1', models.CharField(max_length=128)),
                ('line_2', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('zip_code', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('used', 'Used'), ('notused', 'Not Used'), ('hold', 'Hold')], default='notused', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'addresses',
            },
        ),
    ]
