# Generated by Django 4.0.4 on 2022-05-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.telegramuser'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('name', 'line_1', 'line_2', 'city', 'state', 'zip_code', 'phone')},
        ),
    ]
