# Generated by Django 4.0.4 on 2022-06-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_alter_address_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user_in_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
