# Generated by Django 4.0.4 on 2022-06-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_alter_address_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('usa', 'USA'), ('cz', 'CZ'), ('uk', 'UK')], default='usa', max_length=30),
        ),
    ]
