# Generated by Django 4.0.4 on 2022-06-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0009_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('usa', 'United States'), ('uk', 'United Kingdom'), ('cz', 'Czechia')], default='usa', max_length=30),
        ),
    ]
