# Generated by Django 4.0.6 on 2022-07-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0010_alter_address_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('usa', 'United States'), ('uk', 'United Kingdom'), ('de', 'Germany'), ('lv', 'Latvia')], default='usa', max_length=30),
        ),
    ]
