# Generated by Django 4.0.6 on 2022-07-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0012_alter_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='czk', max_length=32),
            preserve_default=False,
        ),
    ]
