# Generated by Django 4.0.6 on 2022-07-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0013_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
    ]
