# Generated by Django 4.0.4 on 2022-05-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0005_alter_address_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('shop_name', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
